# > Database Options <

# > Subscription Options <

#This is how much money the silver subscription costs
silver-price: 150000

#This is how much money the gold subscription costs
gold-price: 200000

#This is how much money the platinum subscription costs
platinum-price: 350000

#This option edits the chance for gold:
gold-drop-rate: 0.08