# > Database Options <
host: "94.130.143.221"
port: 3306
database: "s152_subs"
username: "u152_XHkqAH9W98"
password: "@b0kpoZeIIBlz4PXQ.685fmF"

# > Subscription Options <

#This is how much money the silver subscription costs
silver-price: 150000

#This is how much money the gold subscription costs
gold-price: 200000

#This is how much money the platinum subscription costs
platinum-price: 350000

#This option edits the chance for gold:
gold-drop-rate: 0.08