package com.subscriptions.subscriptions.enums;

public enum PrepareStatements {

    CREATESILVERTABLE("CREATE TABLE IF NOT EXISTS SILVER(NAME VARCHAR(16) NOT NULL, ID INT(2), PRIMARY KEY (NAME))"),
    CREATEGOLDTABLE("CREATE TABLE IF NOT EXISTS GOLD(NAME VARCHAR(16) NOT NULL, ID INT(2), PRIMARY KEY (NAME))"),
    CREATEPLATINUMTABLE("CREATE TABLE IF NOT EXISTS PLATINUM(NAME VARCHAR(16) NOT NULL, ID INT(2), PRIMARY KEY (NAME))"),

    //Cosmetics:
    CREATEPARTICLESTABLE("CREATE TABLE IF NOT EXISTS PARTICLES(NAME VARCHAR(16) NOT NULL, HEART INT(1), MAGIC INT(1), " +
            "CLOUD INT(1), ENDER INT(1), SPARK INT(1), FLAME INT(1), SNOW INT(1), " +
            "WATER INT(1), SMOKE INT(1), SLIME INT(1), ENCHANTED INT(1), MUSIC INT(1), EMERALD INT(1), PRIMARY KEY (NAME))"),


    GETSILVERDATA("SELECT * FROM SILVER WHERE NAME =?"),
    SETSILVERDATA("INSERT INTO SILVER(NAME, ID) VALUES (?,?)"),

    GETGOLDDATA("SELECT * FROM GOLD WHERE NAME =?"),
    SETGOLDDATA("INSERT INTO GOLD(NAME, ID) VALUES (?,?)"),

    GETPLATINUMDATA("SELECT * FROM PLATINUM WHERE NAME =?"),
    SETPLATINUMDATA("INSERT INTO PLATINUM(NAME, ID) VALUES (?,?)"),

    SETPARTICLEDATA("INSERT INTO PARTICLES(NAME, HEART, MAGIC, CLOUD, ENDER, SPARK, FLAME, SNOW, WATER, SMOKE, SLIME, ENCHANTED, MUSIC, EMERALD)" +
            " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)"),

    GETPARTICLEDATA("SELECT * FROM PARTICLES WHERE NAME =?"),

    HEARTID("HEART"),
    SETHEART("INSERT INTO PARTICLES(NAME, HEART) VALUES(?,?)"),
    UPDATEHEART("UPDATE PARTICLES SET HEART=? WHERE NAME =?"),

    MAGICID("MAGIC"),
    SETMAGIC("INSERT INTO PARTICLES(NAME, MAGIC) VALUES(?,?)"),
    UPDATEMAGIC("UPDATE PARTICLES SET MAGIC=? WHERE NAME =?"),

    CLOUDID("CLOUD"),
    SETCLOUD("INSERT INTO PARTICLES(NAME, CLOUD) VALUES(?,?)"),
    UPDATECLOUD("UPDATE PARTICLES SET CLOUD=? WHERE NAME =?"),

    ENDERID("ENDER"),
    SETENDER("INSERT INTO PARTICLES(NAME, ENDER) VALUES(?,?)"),
    UPDATEENDER("UPDATE PARTICLES SET ENDER=? WHERE NAME =?"),

    SPARKID("SPARK"),
    SETSPARK("INSERT INTO PARTICLES(NAME, SPARK) VALUES(?,?)"),
    UPDATESPARK("UPDATE PARTICLES SET SPARK=? WHERE NAME =?"),

    FLAMEID("FLAME"),
    SETFLAME("INSERT INTO PARTICLES(NAME, FLAME) VALUES(?,?)"),
    UPDATEFLAME("UPDATE PARTICLES SET FLAME=? WHERE NAME =?"),

    SNOWID("SNOW"),
    SETSNOW("INSERT INTO PARTICLES(NAME, SNOW) VALUES(?,?)"),
    UPDATESNOW("UPDATE PARTICLES SET SNOW=? WHERE NAME =?"),

    WATERID("WATER"),
    SETWATER("INSERT INTO PARTICLES(NAME, WATER) VALUES(?,?)"),
    UPDATEWATER("UPDATE PARTICLES SET WATER=? WHERE NAME =?"),

    SMOKEID("SMOKE"),
    SETSMOKE("INSERT INTO PARTICLES(NAME, SMOKE) VALUES(?,?)"),
    UPDATESMOKE("UPDATE PARTICLES SET SMOKE=? WHERE NAME =?"),

    SLIMEID("SLIME"),
    SETSLIME("INSERT INTO PARTICLES(NAME, SLIME) VALUES(?,?)"),
    UPDATESLIME("UPDATE PARTICLES SET SLIME=? WHERE NAME =?"),

    ENCHANTEDID("ENCHANTED"),
    SETENCHANTED("INSERT INTO PARTICLES(NAME, ENCHANTED) VALUES(?,?)"),
    UPDATEENCHANTED("UPDATE PARTICLES SET ENCHANTED=? WHERE NAME =?"),

    MUSICID("MUSIC"),
    SETMUSIC("INSERT INTO PARTICLES(NAME, MUSIC) VALUES(?,?)"),
    UPDATEMUSIC("UPDATE PARTICLES SET MUSIC=? WHERE NAME =?"),

    EMERALDID("EMERALD"),
    SETEMERALD("INSERT INTO PARTICLES(NAME, EMERALD) VALUES(?,?)"),
    UPDATEEMERALD("UPDATE PARTICLES SET EMERALD=? WHERE NAME =?");

    String statement;

    PrepareStatements(String statement) {
        this.statement = statement;
    }

    public String getStatement() {
        return statement;
    }
}
